backend: "https://google.com"

spring:
    application:
        name: backend
    sleuth:
        sampler:
            probability: 1
management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
